<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Artista</h1></div>
    </div>
    <hr>

<script type="text/javascript" language="javascript" class="init">
$(document).ready(function() {
	$('#example').DataTable();
} );
</script> 
<?php
$this->headLink()->appendStylesheet('/css/tabelas/jquery.dataTables.css');
$this->headScript()->prependFile('/js/tabelas/jquery.dataTables.js');   
$this->headScript()->prependFile('/js/tabelas/jquery-1.12.0.min.js');  


$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg == 2)
    echo '<div class="alert alert-info">Atualizado com sucesso<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msg == 1)
     echo '<div class="alert alert-success">Registro cadastrado com sucesso.<button type="button" class="close" data-dismiss="alert">x</button></div>';

?>
   
<h2 class="form-group">Artistas/Bandas cadastradas</h2><br>       
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table id="example" class="table table-striped table-bordered table-bg" cellspacing="0" width="100%">
                <thead class="thead-inverse">
                    <tr class="thead-inverse" >
                        <th>#</th>
                        <th>Album</th>
                        <th >Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->dados as $artista): ?>
                        <tr>
                            <td><?php echo $artista->getId(); ?></td>
                            <td><?php echo $artista->getNome(); ?></td>
                            <td>
                                <a class="btn btn-success" href="<?=
                                $this->url('full-app', ['controller' => 'artista',
                                    'action' => 'index', 'id' => $artista->getId()]);
                                ?>"><div class="glyphicon glyphicon-pencil"></div></a>
                                |
                                <a class="btn btn-danger" href="<?= $this->url('full-app', ['controller' => 'artista',
                                    'action' => 'delete', 'id' => $artista->getId()]);
                                ?>"><div class="glyphicon glyphicon-remove"></div></a>


                            </td>
                        </tr>  
<?php endforeach; ?>

                </tbody>
            </table>
        </div> 
    </div>
</div>
<?php  
  //  echo $this->paginationControl($this->dados, 'Sliding', 'partials/paginator', array('route' => 'defaults/paginator'));
?>
