<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Artistas teste</h1></div>
    </div>
    <hr>
<?php
/**
 * @var $form \Zend\Form\Form
 */


$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg == 2)
    echo '<div class="alert alert-info">Atualizado com sucesso<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msg == 1)
     echo '<div class="alert alert-success">Registro cadastrado com sucesso.<button type="button" class="close" data-dismiss="alert">x</button></div>';

?>
    <div class="table-responsive">
<table class="table table-striped" border="1" width="80%">
    <thead>
        <tr>
            <th>#</th>
            <th>Album</th>
            <th >Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->dados as $artista): ?>
        <tr>
            <td><?php echo $artista->getId();?></td>
            <td><?php echo $artista->getNome();?></td>
             <td>
                <a class="btn btn-success" href="<?= $this->url('full-app', ['controller' => 'artista',
            'action' => 'index', 'id' => $artista->getId()]);
                    ?>"><div class="glyphicon glyphicon-pencil"></div></a>
                    |
                    <a class="btn btn-danger" href="<?=$this->url('full-app',['controller'=>'artista', 
                    'action'=>'delete','id'=>$artista->getId()]);?>"><div class="glyphicon glyphicon-remove"></div></a>
                    
                
            </td>
        </tr>  
        <?php endforeach;?>
        
    </tbody>
</table>
    </div>  
<?php  
    echo $this->paginationControl($this->dados, 'Sliding', 'partials/paginator', array('route' => 'defaults/paginator'));
?>
