
<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Minhas Musicas</h1></div>
    </div>
 <hr>
<script type="text/javascript" language="javascript" class="init">
$(document).ready(function() {
	$('#example').DataTable();
} );
</script>  
<?php
$this->headLink()->appendStylesheet('/css/tabelas/jquery.dataTables.css');
$this->headScript()->prependFile('/js/tabelas/jquery.dataTables.js');   
$this->headScript()->prependFile('/js/tabelas/jquery-1.12.0.min.js'); 


$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg == 2)
    echo '<div class="alert alert-info">Atualizado com sucesso<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msg == 1)
     echo '<div class="alert alert-success">Registro cadastrado com sucesso.<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msgError)
    echo '<div class="alert alert-danger">'.$this->msgError.'<button type="button" class="close" data-dismiss="alert">x</button></div>';

?>
<h2 class="form-group">Lista das musicas</h2><br>
<div class="table-responsive">
<table id="example" class="table table-striped table-bordered display" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Album</th>
            <th>Genero</th>
            <th>Ações</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->dados as $musica): ?>
            <tr>
                <td><?php echo $musica->getId(); ?></td>
                <td><?php echo $musica->getNome(); ?></td>
                <td><?php echo $musica->getAlbum()->getNome(); ?></td> 
                <td><?php echo $musica->getGenero()->getNome(); ?></td> 
            
                <td>
                    <a class="btn btn-success" href="<?= $this->url('full-app', ['controller' => 'musica',
            'action' => 'index', 'id' => $musica->getId()]);
                    ?>"><div class="glyphicon glyphicon-pencil"></div></a>
                    |
                    <a class="btn btn-danger" href="<?=$this->url('full-app',['controller'=>'musica', 
                    'action'=>'delete','id'=>$musica->getId()]);?>"><div class="glyphicon glyphicon-remove"></div></a> 
                    
           

                </td>
              
            </tr>  
<?php endforeach; ?>

    </tbody>
</table>
</div>
