<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Meus Albuns</h1></div>
    </div>
   
       <hr>
<script type="text/javascript" language="javascript" class="init">
$(document).ready(function() {
	$('#albuns').DataTable();
} );
</script> 
<?php
$this->headLink()->appendStylesheet('/css/tabelas/jquery.dataTables.css');
$this->headScript()->prependFile('/js/tabelas/jquery.dataTables.js');   
$this->headScript()->prependFile('/js/tabelas/jquery-1.12.0.min.js'); 

$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg == 2)
    echo '<div class="alert alert-info">Atualizado com sucesso<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msg == 1)
     echo '<div class="alert alert-success">Registro cadastrado com sucesso.<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msgError)
    echo '<div class="alert alert-danger">'.$this->msgError.'<button type="button" class="close" data-dismiss="alert">x</button></div>';
?>

<h2 class="form-group">Lista dos Albuns</h2><br>
 <div class="table-responsive">
<table id="albuns" class="table table-striped table-bordered display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Album</th>
            <th>Artista/Banda</th>
            <th>Produtora</th>
            <th>valor</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->dados as $album): ?>
            <tr>
                <td><?php echo $album->getId(); ?></td>
                <td><?php echo $album->getNome(); ?></td>
                <td><?php  echo $album->getArtista()->getNome(); ?></td>
                <td><?php  echo $album->getProdutora()->getNome(); ?></td>
                <td><?php if($album->getValor() == 0 || $album->getValor() == null)
                                echo 'R$ 0.00';
                            else {
                                echo 'R$ '.$album->getValor();
                            }
                    ?></td>
                <td>
                    <a class="btn btn-success" href="<?= $this->url('full-app', ['controller' => 'album',
            'action' => 'index', 'id' => $album->getId()]);
                    ?>"><div class="glyphicon glyphicon-pencil"></div></a>
                    |
                    <a class="btn btn-danger" href="<?=$this->url('full-app',['controller'=>'album',
                    'action'=>'delete','id'=>$album->getId()]);?>"><div class="glyphicon glyphicon-remove"></div></a>
                    |
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModalMusicas<?php echo $album->getId(); ?>">
                                                     <div class="glyphicon glyphicon-search"></div>
                    </button> 
               <!-- ICINIO MODAL DAS MUSICAS -->                    
                    <div class="modal fade"id="myModalMusicas<?php echo $album->getId(); ?>">
                        <div class="modal-dialog">
                                <div class="modal-content fundo-modal"  >
                                    <div class="modal-header">
                                        <button class="close" aria-hidden="true" type="button" data-dismiss="modal">X</button>
                                        <h2 class="modal-title" align="center">Musicas do Album </h2>
                                        <h3 align="center"><strong><?php echo $album->getNome(); ?></strong></h3>
                                    </div>
                                    <div class="modal-body">
                                        <div class="table-responsive" >    
                                            <table class="table table-striped display" style="background-color: transparent;">
                                                <thead>
                                                    <tr>  

                                                        <th>Musicas</th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                       <?php //   FOREACH PARA PEGAR AS MUSICAS DA ENTIDADE MUSICA PELA ORM ONETOMANY 
                                                        $i= 0;
                                                        $musicas = $album->getMusicas();
                                                            foreach ($musicas as $musica): ?>
                                                            <tr><td>                                                                       
                                                                 <?php
                                                                            if ($musica == null)
                                                                                echo "não a musicas neste album";
                                                                            else
                                                                                echo ++$i . ' - ' . $musica->getNome();
                                                                            ?>                                                                   
                                                            </td><tr>
                                                        <?php endforeach; ?>
                                                    </tr>        
                                                </tbody>

                                            </table>

                                        </div>
                                    </div>
                                    <div class="modal-footer" id="naoImprime">
                                        <button class="btn btn-info " type="button" data-dismiss="modal">Fechar</button>

                                    </div>

                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.FIM DO MODAL MUSICAS -->
                </td>
            </tr>
            
<?php endforeach; ?>

    </tbody>
</table>
       </div>
