<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Meus Albuns</h1></div>
    </div>
   
       <hr>

<?php
use Doctrine\DBAL\DBALException;

$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg == 2)
    echo '<div class="alert alert-info">Atualizado com sucesso<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msg == 1)
     echo '<div class="alert alert-success">Registro cadastrado com sucesso.<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->msgError)
    echo '<div class="alert alert-danger">'.$this->msgError.'<button type="button" class="close" data-dismiss="alert">x</button></div>';
?>
 <div class="table-responsive">
<table class="table table-striped" border="1" width="80%">
    <thead>
        <tr>
            <th>#</th>
            <th>Album</th>
            <th>Artista/Banda</th>
            <th>Produtora</th>
            <th>valor</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->dados as $album): ?>
            <tr>
                <td><?php echo $album->getId(); ?></td>
                <td><?php echo $album->getNome(); ?></td>
                <td><?php  echo $album->getArtista()->getNome(); ?></td>
                <td><?php  echo $album->getProdutora()->getNome(); ?></td>
                <td><?php if($album->getValor() == 0 || $album->getValor() == null)
                                echo 'R$ 0.00';
                            else {
                                echo 'R$ '.$album->getValor();
                            }
                    ?></td>
                <td>
                    <a class="btn btn-success" href="<?= $this->url('full-app', ['controller' => 'album',
            'action' => 'index', 'id' => $album->getId()]);
                    ?>"><div class="glyphicon glyphicon-pencil"></div></a>
                    |
                    <a class="btn btn-danger" href="<?=$this->url('full-app',['controller'=>'album',
                    'action'=>'delete','id'=>$album->getId()]);?>"><div class="glyphicon glyphicon-remove"></div></a>
                    |
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModalMusicas<?php echo $album->getId(); ?>">
                                                     <div class="glyphicon glyphicon-search"></div> </button> 
                                   
                    <div class="modal fade" id="myModalMusicas<?php echo $album->getId(); ?>">
                        <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button class="close" aria-hidden="true" type="button" data-dismiss="modal">X</button>
                                        <h3 class="modal-title" align="center">Musicas do Album </h3>
                                        <h3 align="center"><strong><?php echo $album->getNome(); ?></strong></h3>
                                    </div>
                                    <div class="modal-body">
                                        <h5 class="text-center"><strong>Musicas:</strong></h5>
                                        <div class="table-responsive">    
                                            <table class="table table-striped" id="tblGrid">
                                                <thead id="tblHead">
                                                    <tr>

                                                        <th>Nome</th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <?php
                                                        $i= 0;
                                                        $musicas = $album->getMusicas();
                                                            foreach ($musicas as $musica): ?>
                                                            <tr><td>                                                                       
                                                                 <?php   if ($musica != null){ 
                                                                             echo  ++$i.' - '.$musica->getNome(); 
                                                                 }    
                                                                                                                                                                                  
                                                                ?>                                                                   
                                                            </td><tr>
                                                        <?php endforeach; ?>
                                                    </tr>        
                                                </tbody>

                                            </table>

                                        </div>
                                    </div>
                                    <div class="modal-footer" id="naoImprime">
                                        <button class="btn btn-default " type="button" data-dismiss="modal">Fechar</button>

                                    </div>

                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->
                </td>
            </tr>
            
<?php endforeach; ?>

    </tbody>
</table>
       </div>
