
<div class="container">
    <div class="row">
        <div class="col-lg-6 form-group"><h1>Meus Albuns</h1></div>
    </div>
   
       <hr>

<?php


$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

echo '<br />';
if ($this->msg)
    echo '<div class="alert alert-info">'.$this->msg.'<button type="button" class="close" data-dismiss="alert">x</button></div>';

?>
       <hr>
       </div>
