<?php
$this->headLink()->appendStylesheet('/css/business-frontpage.css');
?>
<header class="business-header">
     
    
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr>

        <div class="row">
            <div class="col-sm-8">
                <h2>Detalhes</h2>
                
                <p>Trabalho Realizado para a Disciplina optativa PHP .</p>
                
            </div>
            <div class="col-sm-4">
                <h2>Alunos</h2>
                <strong>Welinton Dias e William Amaral</strong><br>
                <strong>Professor:</strong></abbr>Giovanni Camargo<br>
                 <br>Teofilo Otoni, MG 
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="../img/rock-music.png" alt="">
                <h2 align="center">Rock 'N' Roll</h2>
                <p align="center">Let´s play Rock.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="../img/sertanejo.jpg" alt="">
                
                <h2 align="center">Sertanejo</h2>
                <p align="center">Descrição</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="../img/electro-music.jpg" alt="">
                <h2 align="center">Musica Eletrônica</h2>
                <p align="center">Descrição</p>
            </div>
        </div>